global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'performance-antipatterns'
    static_configs:
      - targets: 
        - 'host.docker.internal:8080'  # Bad: Improper Instantiation
        - 'host.docker.internal:8081'  # Good: Improper Instantiation
        - 'host.docker.internal:8082'  # Bad: Synchronous I/O
        - 'host.docker.internal:8083'  # Good: Synchronous I/O
        - 'host.docker.internal:8084'  # Bad: Chatty I/O
        - 'host.docker.internal:8085'  # Good: Chatty I/O
        - 'host.docker.internal:8086'  # Bad: No Caching
        - 'host.docker.internal:8087'  # Good: No Caching
        - 'host.docker.internal:8088'  # Bad: Busy Database
        - 'host.docker.internal:8089'  # Good: Busy Database
        - 'host.docker.internal:8090'  # Bad: Retry Storm
        - 'host.docker.internal:8091'  # Good: Retry Storm
